# Generated by Django 3.2.4 on 2021-06-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import space_travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_certification', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=70)),
                ('age', space_travel.models.IntegerRangeField()),
                ('credits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('weight', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.JSONField(default=dict)),
                ('fuel_costs', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
                ('destination_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_destination', to='space_travel.planet')),
                ('origin_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_origin', to='space_travel.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_capacity', models.IntegerField()),
                ('fuel_level', models.IntegerField()),
                ('weight_capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_travel.pilot')),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='location_planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_location', to='space_travel.planet'),
        ),
        migrations.CreateModel(
            name='FuelRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
                ('location_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelrefill_location', to='space_travel.planet')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_travel.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('value', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disabled_at', models.DateTimeField(default=None)),
                ('destination_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_destination', to='space_travel.planet')),
                ('origin_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_origin', to='space_travel.planet')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_travel.pilot')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_travel.travel')),
            ],
        ),
    ]
