# Generated by Django 3.2.4 on 2021-06-22 22:35

from django.db import migrations, models
import space_travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('payload', models.JSONField(default={})),
                ('origin_planet', models.CharField(default='', max_length=70)),
                ('destination_planet', models.CharField(default='', max_length=70)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_certification', models.BigIntegerField(validators=[space_travel.models.certification_validate])),
                ('name', models.CharField(default='', max_length=70)),
                ('age', space_travel.models.IntegerRangeField()),
                ('credits', models.IntegerField(default=0)),
                ('location_planet', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_capacity', models.IntegerField(default=0)),
                ('fuel_level', models.IntegerField(default=0)),
                ('weight_capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
