# Generated by Django 3.2.4 on 2021-06-24 12:21

from django.db import migrations
from space_travel.migrations import insertData

class Migration(migrations.Migration):

    dependencies = [
        ('space_travel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertData),
    ]
